function [scenario, egoVehicle] = testScenario2()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 23-May-2023 15:23:55

% Construct a drivingScenario object.
scenario = drivingScenario('SampleTime', 0.1);

% Add all road segments
roadCenters = [0.1 -0.1 0;
    306.8 -0.1 0];
road(scenario, roadCenters, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [5.2 0 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [11.8032858901585 -0.128689483808387 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [11.8032858901585 -0.128689483808387 0;
    77.6 -2.5 0;
    87.4 -2.5 0;
    93.1 2.4 0;
    102.2 -0.5 0;
    115.8 2 0;
    142.1 -0.9 0;
    214.5 0.7 0;
    298.8 -0.5 0];
speed = [20;20;5;5;5;10;12;20;10];
waittime = [0;0;0;0;0;0;0;0;0];
trajectory(car1, waypoints, speed, waittime);

