function [scenario, egoVehicle] = complicatedACC4()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 09-May-2023 21:52:42
load('mydata.mat', 'positions', 'velocities');
% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0.3 0.2 0;
    302.2 -0.9 0];
road(scenario, roadCenters, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [6.7 0.5 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [18.8 0.2 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints =    [57 -0.1285 0;
73 0.15432 0;
101 0.15224 0;
102 -0.071732 0;
137 0.040693 0;
159 -0.25449 0;
170 -0.26763 0;
179 0.018479 0;
241 0.1675 0;
266 0.26041 0;];
speed =    [16.9;
4.1;
1.2;
5.2;
14.4;
6.5;
15;
5.8;
19;
17.3;
];
trajectory(car1, waypoints, speed);

