function [scenario, egoVehicle] = complicatedACC4()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 09-May-2023 21:52:42
load('mydata.mat', 'positions', 'velocities');
% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0.3 0.2 0;
    302.2 -0.9 0];
road(scenario, roadCenters, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [6.7 0.5 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [18.8 0.2 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints =    [11.0000   -0.1860         0;
   45.0000    0.1810         0;
  119.0000   -0.2910         0;
  194.0000   -0.2993         0;
  223.0000    0.0689         0;
  225.0000   -0.0614         0;
  234.0000   -0.1774         0;
  262.0000    0.1017         0;
  274.0000   -0.0167         0;
  275.0000    0.1400         0;];
speed =    [16.0000;
    1.6000;
    8.0000;
    2.8000;
   18.1000;
    7.0000;
    9.0000;
   10.6000;
    0.8000;
   11.6000;];
trajectory(car1, waypoints, speed);

