function [scenario, egoVehicle] = complicated1ACC()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.13 (R2022b) and Automated Driving Toolbox 3.6 (R2022b).
% Generated on: 05-May-2023 21:37:57

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0.2 0.1 0;
    226.2 0.2 0];
road(scenario, roadCenters, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [7.4 0.2 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [18.8 -0.1 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [18.8 -0.1 0;
    66.8 0 0;
    109.7 0.4 0;
    129.4 0.4 0;
    142.4 0.3 0;
    158.8 0.9 0;
    168.4 0.3 0;
    180.3 0.3 0;
    190.8 -0.1 0;
    200.7 0.3 0;
    209.4 1.3 0;
    222.8 1.6 0];
speed = [5;8;20;5;10;3;5;6;9;10;23;11];
waittime = [0;0;0;0;0;0;0;0;0;0;0;0];
trajectory(car1, waypoints, speed, waittime);

